spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tattoorg_db?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: org.hibernate.dialect.MySQL5Dialect
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
  jpa:
    hibernate:
      ddl-auto: none

bezkoder:
  app:
    jwtSecret: tattooSecret
    jwtExpirationMs: 86400000
